name: workflow

on:
  push:
    - main
  paths_ignore:
    - "README.md"

jobs:
 integration:
   name: Continuous Integration
   runs-on: ubuntu-latest
   steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Lint code
        uses: echo "Linting repository"

      - name: Run unit tests
        uses: echo "Running unit tests"  
        